language: objective-c
osx_image: xcode8.1
xcode_project: iMusic.xcodeproj
xcode_scheme: iMusicTests
bundler_args: --retry 3
branches:
    only:
        - develop
        - master
notifications:
    email: false
before_install:
    - gem install bundler
    - bundle install && brew bundle
script:
    - bundle update scan
    - bundle update fastlane
    - bundle exec fastlane tests