osx_image: xcode8.1
language: objective-c
xcode_project: iMusicProject.xcodeproj
xcode_scheme: iMusicTests
branches:
    only:
        - develop
        - master
notifications:
    email: false
before_install:
    - gem install bundler
    - bundle install
script:
    - bundle exec fastlane tests